#!/bin/sh

# A dmenu password prompt script.
# Gives a dmenu prompt asking for password, password will not be seen.
# Uses $1 to set the prompt.
# For example:
# `./dmenupass "Enter password:"`

dmenu -fn Monospace-18 -sb "#d79921" -sf "#1d2021" -nf "#000000" -nb "#000000" -p "$1" <&- && echo

