#!/usr/bin/env bash

echo Hello $1

case "$1" in
	-m)
		youtube-dl --extract-audio --audio-format mp3 $2
		;;
	*)
		cat << EOF
		Usage: $0 [options] URL

		-h | --help           Display this help.

		-m |-music            Download the song as a mp3 file and save it in the current directory
EOF

		exit 1
		;;
esac
